export const DIFFICULTY_MAP: Map<string, string> = new Map([
    ['NA', 'NA'],
    ['EXTREME_DEMON', 'Extreme Demon'],
    ['INSANE_DEMON', 'Insane Demon'],
    ['HARD_DEMON', 'Hard Demon'],
    ['MEDIUM_DEMON', 'Medium Demon'],
    ['EASY_DEMON', 'Easy Demon'],
    ['OBSIDIAN_DEMON', 'Obsidian Demon'],
    ['AZURITE_DEMON', 'Azurite Demon'],
    ['AMETHYST_DEMON', 'Amethyst Demon'],
    ['ONYX_DEMON', 'Onyx Demon'],
    ['PEARL_DEMON', 'Pearl Demon'],
    ['DIAMOND_DEMON', 'Diamond Demon'],
    ['RUBY_DEMON', 'Ruby Demon'],
    ['EMERALD_DEMON', 'Emerald Demon'],
    ['JADE_DEMON', 'Jade Demon'],
    ['SAPPHIRE_DEMON', 'Sapphire Demon'],
    ['PLATINUM_DEMON', 'Platinum Demon'],
    ['AMBER_DEMON', 'Amber Demon'],
    ['GOLD_DEMON', 'Gold Demon'],
    ['SILVER_DEMON', 'Silver Demon'],
    ['BRONZE_DEMON', 'Bronze Demon'],
    ['BEGINNER_DEMON', 'Beginner Demon'],
    ['INSANE', 'Insane'],
    ['HARDER', 'Harder'],
    ['HARD', 'Hard'],
    ['NORMAL', 'Normal'],
    ['EASY', 'Easy'],
    ['AUTO', 'Auto']
]);
